:toc:
= Documentation for Developers

== Getting started

=== Installation of Tools

To get started in the project install the following Tools:

Node and NPM::
Download from https://nodejs.org/en/, choose the LTS version

IntelliJ from JetBrains::
The "ultimate edition" will allow also JavaScript development.

Vue.js Plugin from Jetbrains for IntelliJ::
Ensure that you install the one from JetBrains, not the other Vue.js plugin. +
https://plugins.jetbrains.com/plugin/9442-vue-js

AsciiDoc Plugin for IntelliJ::
This will allow you to preview and edit the *.adoc-files in the project.
They are used for documentation.

=== Configuration of the tools

In IntelliJ disable the option "Use safe write", otherwise the hot-reload functionality will not work.

=== Developing the application

Run once every time the dependencies change:

----
npm install
----

To run using hot-reload development mode use the following command.
This will forward all requests to URLs below _/rest_ to _https://latest.dukecon.org/javaland/2017_.
It will also connect to the Dukecon's Keycloak instance.
Therefore you'll need to be online when developing in this mode.
See _conf/index.js_ for details on how to configure this.

----
npm run dev
----

=== Testing the application

To run all unit tests run

----
npm run unit
----

You can run all tests in an infinite loop

----
npm run unitloop
----

NOTE: It might happen that PhantomJS terminates due to inactivity.
In this case open up the URL in Chrome: http://localhost:9876/

To run the integration tests you need a local Chrome browser installed.
You'll also need a connection to the internet as this will start the frontend in development mode that will proxy all _/rest_ resources to _https://latest.dukecon.org/javaland/2017_.
It will also connect to the Dukecon's Keycloak instance.
Use the following command to run them:

----
npm run e2e
----

To run the integration tests in a Chrome browser in the background (headless) use the following command.
At the time this is written this still need a display when build on Travis CI using _xvfb-run_.
See _.travis.yml_ for details.

----
npm run e2e_headless
----

== Offline Functionality

This application is a PWA (https://en.wikipedia.org/wiki/Progressive_web_app[Progressive Web App]).

All static web resources will be pre-loaded by the service worker.

*Caching Strategy _fastest_:*
All calls to the _/rest_ URLs will be cached and serviced with the previously downloaded version.
If the application is online, a new version will be fetched from the network and will be returned by the next request.

Future versions might differentiate between URLs and choose _networkFirst_ to wait for a given time to get a fresh response.

See _webpack.prod.conf.js_ section _SWPrecacheWebpackPlugin_ on how to configure it.
From a developer's point of view you should be able to develop the application in offline mode and it will 'just work' in offline mode.

Offline functionality is not available in development mode.
It is only available in production mode (that is: when you run _npm run build_).

To test the offline functionality you will usually deploy it to a server and you'll need the REST resources to be available in a relative path.

To test it locally there is a switch in Conference.js to run it locally for the JavaLand conference:

Run once to install serve globally
----
npm install -g serve
----

Run after every change of the source

----
npm run build
serve dist
----

== Authentication

This project uses Keycloak for authentication: http://www.keycloak.org/

Keycloak needs to be initialized first, as it will use URL redirects that would other wise interfere with the Vue.js router.
The Keycloak client library is wrapped in DuekconKeycloak.js as a singleton for the project.

== Data Model

The application uses a global data model for events and conference data.
It is loaded by Conference.js.
To all other components of the application it is readonly.
But they will be updated asynchronously when the data is loaded initially, they might be updated with new data periodically as well in the future.
Use the references returned to bind them to your model.

== Components

A Vue.js app is broken down to components.
Each route will be one component.
Components for each route are registered in _main.js_.

Best practices:

* If the page will interact with the route, i.e. to extract a URL parameter, it can be helpful to separate this part from the real logic of the page.
The _SpeakerPage.vue (interacts with the route) and _Speaker.vue_ (displays speaker data and can be re-used) is a good example.

== Internationalization

This application used https://kazupon.github.io/vue-i18n/en/[vue-i18n].

Add all messages keys to _Internationalization.js_.
To present a translated key in your component, add code like this in JavaScript or the HTML templates.

[source,javascript]
.Code to be used in JavaScript
----
$t('imprint')
----

[source,html]
.Code to be used as part of HTML Template
----
<a>{{ $t('imprint') }}</a>
----

== Localization

To show dates and times for different locales, we use _https://momentjs.com/docs/[MomentJS]_.

We don't use a global setting for the locale of MomentJS to support calculated functions for localized dates.
Please use the following sample code to format a given date:

[source,javascript]
----
// pick any given date
Moment(this.event.start)
  // set the locale for this instance
  .locale(this.$i18n.locale)
  // format it as needed
  .format('dddd, Do MMM, HH:mm')
----

At the moment only the en- (default) and de-locales are imported, seel _ContextReplacementPlugin_ in _webpack.base.conf.js_.

== Miscellaneous

* All router views are cached using the _<keep-alive/>_ tag. This avoid long initial rendering times when returning on the _SpeakersPage_. It should be re-evaluated if this needs too much RAM.
* If you have multiple images on a page, consider lazy loading of the images (see _SpeakersPage.vue_ uses _VueLazyLoad_ for this.
* The scrolling position for each page is saved and restored on route navigation (see initialization of _VueRouter_).
This is not using the HTML5 router as this requires the server file handling to be updated as all routes of the frontend will also appear as bookmarks in the backend.

== Optimization for production

The command _npm run build_ creates the folder _dist_.
This is served as static pages from a production server.

You can analyze the contents of the created files by running _npm run build --report_. This creates and serves a _report.html_ file in the _dist_ folder.
Use it to analyze the contents and sizes of the bundle created.
The smaller the size, the faster the app will load.

The following files are not needed in production and should be excluded:

report.html::
Bundle analyzer report (created by _npm run build --report_)

*.map::
Source Map Files

== Testing

=== Testing components for unit tests

Some best practices - see the unit tests in _test/unit/specs_ for examples.

. Always test one component at a time.
. To mock calls to other components, use the _sinon_ Sandbox
. To mock XMLHttpRequest calls by _axios_, use _moxios_
. To test a Vue component you'll need to crate a _Vue_ instance and mount it.
This can contain a minimal template and also other components.
. Once something changes in the view, wrap the next part in _vm.$nextTick_
