:toc:
# Documentation for Developers

## Getting started

### Installation of Tools

To get started in the project install the following Tools:

Node and NPM::
Download from https://nodejs.org/en/, choose the LTS version

IntelliJ from JetBrains::
The "ultimate edition" will allow also JavaScript development.

Vue.js Plugin from Jetbrains for IntelliJ::
Ensure that you install the one from JetBrains, not the other Vue.js plugin. +
https://plugins.jetbrains.com/plugin/9442-vue-js

AsciiDoc Plugin for IntelliJ::
This will allow you to preview and edit the *.adoc-files in the project.
They are used for documentation.

### Configuration of the tools

In IntelliJ disable the option "Use safe write", otherwise the hot-reload functionality will not work.

### Developing the application

Run once every time the dependencies change:

----
npm install
----

To run using hot-reload development mode use the following command.
This will forward all requests to URLs below _/rest_ to _https://latest.dukecon.org/javaland/2017_.
It will also connect to the Dukecon's Keycloak instance.
Therefore you'll need to be online when developing in this mode.
See _conf/index.js_ for details on how to configure this.

----
npm run dev
----

### Testing the application

To run all unit tests run

----
npm run unit
----

To run the integration tests you need a local Chrome browser installed.
You'll also need a connection to the internet as this will start the frontend in development mode that will proxy all _/rest_ resources to _https://latest.dukecon.org/javaland/2017_.
It will also connect to the Dukecon's Keycloak instance.
Use the following command to run them:

----
npm run e2e
----

To run the integration tests in a Chrome browser in the background (headless) use the following command.
At the time this is written this still need a display when build on Travis CI using _xvfb-run_.
See _.travis.yml_ for details.

----
npm run e2e_headless
----

## Offline Functionality

This application is a PWA (https://en.wikipedia.org/wiki/Progressive_web_app[Progressive Web App]).

All static web resources will be pre-loaded by the service worker.
All calls to the _/rest_ URLs will be cached and service with the previously downloaded version if the app is offline.
From a developer's point of view you should be able to develop the application in offline mode and it will 'just work' in offline mode.

Offline functionality is not available in development mode.
It is only available in production mode (that is: when you run _npm run build_).

To test the offline functionality you will usually deploy it to a server and you'll need the REST resources to be available in a relative path.

To test it locally there is a switch in Conference.js to run it locally for the JavaLand conference:

----
npm run build
npm install -g serve
serve dist
----

## Authentication

This project uses Keycloak for authentication: http://www.keycloak.org/

Keycloak needs to be initialized first, as it will use URL redirects that would other wise interfere with the Vue.js router.
The Keycloak client library is wrapped in DuekconKeycloak.js as a singleton for the project.

## Data Model

The application uses a global data model for events and conference data.
It is loaded by Conference.js.
To all other components of the application it is readonly.
But they will be updated asynchronously when the data is loaded initially, they might be updated with new data periodically as well in the future.
Use the references returned to bind them to your model.
